name=input("Enter your name")
con=int(input("Enter your contact number"))
email=input("Enter your email")
bdate=input("Enter your birth date")
bmonth=input("Enter your birth month")
byear=input("Enter your birth year")
print("::Your Details:: ")
print("Name :: ",name)
print("Contact number :: ",con)  
print("Email :: ",email)
print("Birth Date :: ",bdate,"/",bmonth,"/",byear)